version: '3.1'

 

services:
  database:
    image: asanjena/mongo
    restart: always
    ports:
      - 27017:27017

 

  sparta-app:
    image: asanjena/alema_docker_app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DB_HOST=database:27017/posts
    command: >
      sh -c "npm install && npm start"